version: 0.0
os: linux

files:
  - source: /
    destination: /opt/beautyonmove/

hooks:
  BeforeInstall:
    - location: aws/scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: aws/scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws/scripts/start-application.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: aws/scripts/stop-application.sh
      timeout: 300
      runas: root 