version: 0.0
os: linux

files:
  - source: app-release.apk
    destination: /var/www/html/beauty-on-the-move.apk

hooks:
  AfterInstall:
    - location: scripts/setup-apk-download.sh
      timeout: 300
      runas: root 