AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for BeautyOnTheMove Android app deployment'

Parameters:
  GitHubRepo:
    Type: String
    Description: "GitHub repository name (format: owner/repo)"
    Default: "KTRapha/BeautyOnTheMove"
    AllowedPattern: "[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+"

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: "VPC ID"

  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: "Public Subnet 1"

  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: "Public Subnet 2"

  UsePermissionBoundary:
    Type: String
    Description: "Whether to use permission boundary (true/false)"
    Default: "false"
    AllowedValues: ["true", "false"]

  PermissionBoundaryArn:
    Type: String
    Description: "ARN of the permission boundary to apply to IAM roles (optional)"
    Default: ""
    AllowedPattern: "^$|^arn:aws:iam::[0-9]{12}:policy/.*$"

Resources:
  DeploymentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'botm-deploy-${AWS::AccountId}-${AWS::Region}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for BeautyOnTheMove EC2 instances
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0

  EC2InstanceProfile:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'BeautyOnTheMoveEC2Role-${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: CodeDeployPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:List*
                Resource:
                  - !Sub 'arn:aws:s3:::${DeploymentBucket}'
                  - !Sub 'arn:aws:s3:::${DeploymentBucket}/*'
                  - 'arn:aws:s3:::ktrapha-beautyonmove-android-deployments'
                  - 'arn:aws:s3:::ktrapha-beautyonmove-android-deployments/*'

  EC2InstanceProfileAttachment:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub 'BeautyOnTheMoveEC2InstanceProfile-${AWS::StackName}'
      Roles:
        - !Ref EC2InstanceProfile

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: BOTMTargetGroup
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPC
      TargetType: instance
      HealthCheckPath: /
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 2

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: BeautyOnTheMoveALB
      Scheme: internet-facing
      Type: application
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      SecurityGroups:
        - !Ref EC2SecurityGroup

  LoadBalancerListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: BeautyOnTheMoveLaunchTemplate
      LaunchTemplateData:
        ImageId: ami-0c02fb55956c7d316
        InstanceType: t3.medium
        IamInstanceProfile:
          Name: !Ref EC2InstanceProfileAttachment
        SecurityGroupIds:
          - !Ref EC2SecurityGroup
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y ruby wget
            yum install -y httpd
            systemctl start httpd
            systemctl enable httpd
            cd /home/ec2-user
            wget https://aws-codedeploy-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/latest/install
            chmod +x ./install
            ./install auto
            systemctl start codedeploy-agent
            systemctl enable codedeploy-agent

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: BeautyOnTheMoveASG
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 1
      VPCZoneIdentifier:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      TargetGroupARNs:
        - !Ref TargetGroup

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: BeautyOnTheMoveApp
      ComputePlatform: Server

  CodeDeployServiceRoleWithoutBoundary:
    Type: AWS::IAM::Role
    Condition: NoPermissionBoundary
    Properties:
      RoleName: !Sub 'BeautyOnTheMoveCodeDeployRole-${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

  GitHubActionsRoleWithoutBoundary:
    Type: AWS::IAM::Role
    Condition: NoPermissionBoundary
    Properties:
      RoleName: !Sub 'GitHubActionsCodeDeployRole-${AWS::StackName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'token.actions.githubusercontent.com:aud': 'sts.amazonaws.com'
              StringLike:
                'token.actions.githubusercontent.com:sub': !Sub 'repo:${GitHubRepo}:*'
      Policies:
        - PolicyName: CodeDeployAndS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:CreateBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${DeploymentBucket}'
                  - !Sub 'arn:aws:s3:::${DeploymentBucket}/*'
                  - 'arn:aws:s3:::ktrapha-beautyonmove-android-deployments'
                  - 'arn:aws:s3:::ktrapha-beautyonmove-android-deployments/*'
              - Effect: Allow
                Action:
                  - codedeploy:*
                Resource: '*'

  CodeDeployDeploymentGroupWithoutBoundary:
    Type: AWS::CodeDeploy::DeploymentGroup
    Condition: NoPermissionBoundary
    Properties:
      ApplicationName: !Ref CodeDeployApplication
      DeploymentGroupName: BeautyOnTheMoveDeploymentGroupWithoutBoundary
      DeploymentStyle:
        DeploymentType: IN_PLACE
        DeploymentOption: WITH_TRAFFIC_CONTROL
      AutoScalingGroups:
        - !Ref AutoScalingGroup
      ServiceRoleArn: !GetAtt CodeDeployServiceRoleWithoutBoundary.Arn
      LoadBalancerInfo:
        TargetGroupInfoList:
          - Name: BOTMTargetGroup

Conditions:
  HasPermissionBoundary: !Not [!Equals [!Ref PermissionBoundaryArn, ""]]
  NoPermissionBoundary: !Equals [!Ref PermissionBoundaryArn, ""]

Outputs:
  LoadBalancerDNS:
    Description: DNS name of the load balancer
    Value: !GetAtt LoadBalancer.DNSName
    Export:
      Name: !Sub '${AWS::StackName}-LoadBalancerDNS'

  S3BucketName:
    Description: Name of the S3 bucket for deployment artifacts
    Value: !Ref DeploymentBucket
    Export:
      Name: !Sub '${AWS::StackName}-S3BucketName'

  CodeDeployApplicationName:
    Description: Name of the CodeDeploy application
    Value: !Ref CodeDeployApplication
    Export:
      Name: !Sub '${AWS::StackName}-CodeDeployApplicationName'

  CodeDeployDeploymentGroupNameWithoutBoundary:
    Description: Name of the CodeDeploy deployment group (without permission boundary)
    Condition: NoPermissionBoundary
    Value: !Ref CodeDeployDeploymentGroupWithoutBoundary
    Export:
      Name: !Sub '${AWS::StackName}-CodeDeployDeploymentGroupNameWithoutBoundary'

  GitHubActionsRoleARNWithoutBoundary:
    Description: ARN of the IAM role for GitHub Actions (without permission boundary)
    Condition: NoPermissionBoundary
    Value: !GetAtt GitHubActionsRoleWithoutBoundary.Arn
    Export:
      Name: !Sub '${AWS::StackName}-GitHubActionsRoleARNWithoutBoundary'
