name: Deploy Android App to AWS

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: us-east-1  # Change to your preferred region
  APPLICATION_NAME: BeautyOnTheMoveApp
  DEPLOYMENT_GROUP_NAME: BeautyOnTheMoveDeploymentGroupWithoutBoundary

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      
    - name: Fix gradlew permissions and line endings
      run: |
        cd android
        chmod +x gradlew
        # Convert Windows line endings to Unix line endings using tr
        tr -d '\r' < gradlew > gradlew.tmp && mv gradlew.tmp gradlew
        chmod +x gradlew
        cd ..
        
    - name: Debug environment
      run: |
        echo "Java version:"
        java -version
        echo "Gradle version:"
        cd android && ./gradlew --version && cd ..
        echo "Android SDK location:"
        echo $ANDROID_HOME
        echo "Build tools version:"
        ls $ANDROID_HOME/build-tools/
        
    - name: Build Android APK
      run: |
        cd android
        ./gradlew assembleRelease --info
        cd ..
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::665802315326:role/GitHubActionsCodeDeployRole-BeautyOnTheMove-Android-Stack
        role-session-name: GitHubActions
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Create deployment package
      run: |
        mkdir -p deployment-package
        cp android/app/build/outputs/apk/release/app-release.apk deployment-package/
        cp BeautyOnTheMove-Android/appspec.yml deployment-package/
        cp -r BeautyOnTheMove-Android/scripts deployment-package/
        
        # Fix script permissions and line endings
        echo "🔧 Fixing script permissions and line endings..."
        find deployment-package/scripts -name "*.sh" -exec chmod +x {} \;
        find deployment-package/scripts -name "*.sh" -exec tr -d '\r' < {} > {}.tmp \; -exec mv {}.tmp {} \;
        find deployment-package/scripts -name "*.sh" -exec chmod +x {} \;
        
        # Debug: Show package contents
        echo "📋 Deployment package contents:"
        find deployment-package -type f -exec ls -la {} \;
        
        echo "📦 Creating deployment ZIP package..."
        cd deployment-package
        zip -r ../deployment-package.zip .
        cd ..
        
        # Debug: Show ZIP contents
        echo "📋 ZIP package contents:"
        unzip -l deployment-package.zip
        
    - name: Upload to S3
      run: |
        DEPLOYMENT_KEY="deployments/$(date +%Y%m%d-%H%M%S)/deployment-package.zip"
        echo "📤 Uploading deployment package to S3: $DEPLOYMENT_KEY"
        aws s3 cp deployment-package.zip s3://${{ secrets.NEW_S3_BUCKET_NAME }}/$DEPLOYMENT_KEY
        
        # Store the deployment key for later use
        echo "DEPLOYMENT_KEY=$DEPLOYMENT_KEY" >> $GITHUB_ENV
        
    - name: Check deployment group and instances
      run: |
        echo "🔍 Checking deployment group configuration..."
        aws deploy get-deployment-group \
          --application-name ${{ env.APPLICATION_NAME }} \
          --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }}
        
        echo "🔍 Checking Auto Scaling Group status..."
        ASG_NAME=$(aws deploy get-deployment-group \
          --application-name ${{ env.APPLICATION_NAME }} \
          --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} \
          --query 'deploymentGroupInfo.autoScalingGroups[0].name' \
          --output text)
        
        if [ "$ASG_NAME" != "None" ] && [ -n "$ASG_NAME" ]; then
          echo "Auto Scaling Group: $ASG_NAME"
          aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names "$ASG_NAME"
          
          echo "🔍 Checking Auto Scaling Group instances..."
          aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-names "$ASG_NAME" \
            --query 'AutoScalingGroups[0].Instances[*].[InstanceId,HealthStatus,LifecycleState]' \
            --output table
        else
          echo "No Auto Scaling Group found in deployment group"
        fi
        
        echo "🔍 Checking target group status..."
        TARGET_GROUP_NAME=$(aws deploy get-deployment-group \
          --application-name ${{ env.APPLICATION_NAME }} \
          --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} \
          --query 'deploymentGroupInfo.loadBalancerInfo.targetGroupInfoList[0].name' \
          --output text)
        
        if [ "$TARGET_GROUP_NAME" != "None" ] && [ -n "$TARGET_GROUP_NAME" ]; then
          echo "Target Group: $TARGET_GROUP_NAME"
          aws elbv2 describe-target-health --target-group-arn $(aws elbv2 describe-target-groups --names "$TARGET_GROUP_NAME" --query 'TargetGroups[0].TargetGroupArn' --output text) || echo "Could not get target group health"
        else
          echo "No target group found in deployment group"
        fi
        
    - name: Create CodeDeploy deployment
      run: |
        echo "🚀 Creating CodeDeploy deployment..."
        DEPLOYMENT_RESPONSE=$(aws deploy create-deployment \
          --application-name ${{ env.APPLICATION_NAME }} \
          --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=${{ secrets.NEW_S3_BUCKET_NAME }},key=${{ env.DEPLOYMENT_KEY }},bundleType=zip \
          --deployment-config-name CodeDeployDefault.OneAtATime \
          --description "Deployment from GitHub Actions")
        
        echo "📋 Deployment Response: $DEPLOYMENT_RESPONSE"
        
        # Extract deployment ID from response
        DEPLOYMENT_ID=$(echo "$DEPLOYMENT_RESPONSE" | jq -r '.deploymentId')
        
        if [ "$DEPLOYMENT_ID" = "null" ] || [ -z "$DEPLOYMENT_ID" ]; then
          echo "❌ Failed to create deployment or get deployment ID"
          echo "Full response: $DEPLOYMENT_RESPONSE"
          exit 1
        fi
        
        echo "✅ Deployment created successfully with ID: $DEPLOYMENT_ID"
        echo "DEPLOYMENT_ID=$DEPLOYMENT_ID" >> $GITHUB_ENV
        
    - name: Get deployment ID and check status
      run: |
        echo "🔍 Using deployment ID from previous step: ${{ env.DEPLOYMENT_ID }}"
        
        if [ -z "${{ env.DEPLOYMENT_ID }}" ]; then
          echo "❌ No deployment ID available from previous step"
          exit 1
        fi
        
        echo "🔍 Checking deployment status..."
        aws deploy get-deployment --deployment-id "${{ env.DEPLOYMENT_ID }}"
        
        echo "🔍 Getting deployment instances..."
        aws deploy list-deployment-instances --deployment-id "${{ env.DEPLOYMENT_ID }}" || echo "No instances found"
        
        echo "🔍 Getting deployment events..."
        INSTANCE_ID=$(aws deploy list-deployment-instances --deployment-id "${{ env.DEPLOYMENT_ID }}" --query 'instancesList[0]' --output text)
        if [ "$INSTANCE_ID" != "None" ] && [ -n "$INSTANCE_ID" ]; then
          aws deploy get-deployment-instance --deployment-id "${{ env.DEPLOYMENT_ID }}" --instance-id "$INSTANCE_ID"
        else
          echo "No instances available for detailed debugging"
        fi
        
        echo "🔍 Checking Auto Scaling Group status..."
        ASG_NAME=$(aws deploy get-deployment-group \
          --application-name ${{ env.APPLICATION_NAME }} \
          --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} \
          --query 'deploymentGroupInfo.autoScalingGroups[0].name' \
          --output text)
        
        if [ "$ASG_NAME" != "None" ] && [ -n "$ASG_NAME" ]; then
          echo "Auto Scaling Group: $ASG_NAME"
          aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-names "$ASG_NAME" \
            --query 'AutoScalingGroups[0].Instances[*].[InstanceId,HealthStatus,LifecycleState]' \
            --output table
        fi
        
    - name: Wait for deployment with better error handling
      run: |
        echo "⏳ Waiting for deployment ${{ env.DEPLOYMENT_ID }} to complete..."
        
        if [ -z "${{ env.DEPLOYMENT_ID }}" ]; then
          echo "❌ No deployment ID available from previous step"
          exit 1
        fi
        
        # Wait for deployment with timeout and better error reporting
        if aws deploy wait deployment-successful --deployment-id "${{ env.DEPLOYMENT_ID }}" --cli-read-timeout 300; then
          echo "✅ Deployment completed successfully!"
        else
          echo "❌ Deployment failed or timed out"
          echo "🔍 Getting final deployment status..."
          aws deploy get-deployment --deployment-id "${{ env.DEPLOYMENT_ID }}"
          
          echo "🔍 Getting deployment instances..."
          aws deploy list-deployment-instances --deployment-id "${{ env.DEPLOYMENT_ID }}" || echo "No instances found"
          
          echo "🔍 Getting deployment events..."
          INSTANCE_ID=$(aws deploy list-deployment-instances --deployment-id "${{ env.DEPLOYMENT_ID }}" --query 'instancesList[0]' --output text)
          if [ "$INSTANCE_ID" != "None" ] && [ -n "$INSTANCE_ID" ]; then
            aws deploy get-deployment-instance --deployment-id "${{ env.DEPLOYMENT_ID }}" --instance-id "$INSTANCE_ID"
          else
            echo "No instances available for detailed debugging"
          fi
          
          echo "🔍 Checking Auto Scaling Group status..."
          ASG_NAME=$(aws deploy get-deployment-group \
            --application-name ${{ env.APPLICATION_NAME }} \
            --deployment-group-name ${{ env.DEPLOYMENT_GROUP_NAME }} \
            --query 'deploymentGroupInfo.autoScalingGroups[0].name' \
            --output text)
          
          if [ "$ASG_NAME" != "None" ] && [ -n "$ASG_NAME" ]; then
            echo "Auto Scaling Group: $ASG_NAME"
            aws autoscaling describe-auto-scaling-groups \
              --auto-scaling-group-names "$ASG_NAME" \
              --query 'AutoScalingGroups[0].Instances[*].[InstanceId,HealthStatus,LifecycleState]' \
              --output table
          fi
          
          exit 1
        fi 